CREATE TABLE IF NOT EXISTS candles_v3 (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  symbol           TEXT    NOT NULL,
  timeframe        TEXT    NOT NULL,
  date             TEXT    NOT NULL,
  timestamp        TEXT    NOT NULL,
  open             REAL    NOT NULL,
  high             REAL    NOT NULL,
  low              REAL    NOT NULL,
  close            REAL    NOT NULL,
  volume           REAL    NOT NULL DEFAULT 0,
  volume_sma20     REAL    NOT NULL DEFAULT 0,
  sma20            REAL    NOT NULL DEFAULT 0,
  sma50            REAL    NOT NULL DEFAULT 0,
  sma200           REAL    NOT NULL DEFAULT 0,
  ema9             REAL    NOT NULL DEFAULT 0,
  ema20            REAL    NOT NULL DEFAULT 0,
  ema50            REAL    NOT NULL DEFAULT 0,
  ema200           REAL    NOT NULL DEFAULT 0,
  macd             REAL    NOT NULL DEFAULT 0,
  macd_signal      REAL    NOT NULL DEFAULT 0,
  macd_histogram   REAL    NOT NULL DEFAULT 0,
  adx              REAL    NOT NULL DEFAULT 0,
  di_plus          REAL    NOT NULL DEFAULT 0,
  di_minus         REAL    NOT NULL DEFAULT 0,
  rsi9             REAL    NOT NULL DEFAULT 0,
  rsi14            REAL    NOT NULL DEFAULT 0,
  rsi_trend        TEXT    NOT NULL DEFAULT 'FLAT',
  stoch_rsi_k      REAL    NOT NULL DEFAULT 0,
  stoch_rsi_d      REAL    NOT NULL DEFAULT 0,
  cci              REAL    NOT NULL DEFAULT 0,
  pivot_point      REAL    NOT NULL DEFAULT 0,
  r1               REAL    NOT NULL DEFAULT 0,
  r2               REAL    NOT NULL DEFAULT 0,
  r3               REAL    NOT NULL DEFAULT 0,
  s1               REAL    NOT NULL DEFAULT 0,
  s2               REAL    NOT NULL DEFAULT 0,
  s3               REAL    NOT NULL DEFAULT 0,
  kijun            REAL    NOT NULL DEFAULT 0,
  tenkan           REAL    NOT NULL DEFAULT 0,
  senkou_a         REAL    NOT NULL DEFAULT 0,
  senkou_b         REAL    NOT NULL DEFAULT 0,
  atr14            REAL    NOT NULL DEFAULT 0,
  bb_upper         REAL    NOT NULL DEFAULT 0,
  bb_middle        REAL    NOT NULL DEFAULT 0,
  bb_lower         REAL    NOT NULL DEFAULT 0,
  keltner_upper    REAL    NOT NULL DEFAULT 0,
  keltner_middle   REAL    NOT NULL DEFAULT 0,
  keltner_lower    REAL    NOT NULL DEFAULT 0,
  hist_vol             REAL    NOT NULL DEFAULT 0,
  price_above_cloud    INTEGER NOT NULL DEFAULT 0,
  price_above_kijun    INTEGER NOT NULL DEFAULT 0,
  inside_bar           INTEGER NOT NULL DEFAULT 0,
  rsi_divergence       INTEGER NOT NULL DEFAULT 0,

  UNIQUE (symbol, timeframe, date)
);
